django_transit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('map.urls')),
]

main/urls.py
"""Defines URL patterns for main."""
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
]

map/urls.py
"""Defines URL patterns for map app."""
from django.urls import path
from . import views

app_name = "map"
urlpatterns = [
    # Map:
    path('map/', views.map_hello_world, name='map'),

    # Socket Test:
    path('socket-test/', views.socket_view, name='socket-page'),

    # AJAX Test:
    path('ajax-test/', views.ajax_view, name='ajax-page'),
    path('ajax-hidden/', views.ajax_background_request_handler, name='ajax-hidden'),  # not seen by user, for
    # background processing use only

    # Location AJAX Test:
    path('location-test/', views.location_view, name='location-page'),
    path('location-test-ajax/', views.location_test_ajax_handler, name='location-ajax'),

    # Location Socket Test:
    path('location-socket-test/', views.location_socket_view, name='location-socket-page'),

]

main/models.py
from django.db import models

# Create your models here.

map/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    """Home page."""
    return render(request, 'main/index.html')

map/views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse
from django.conf import settings

import socketio
sio = socketio.Server(async_mode='threading')


# Create your views here.

"""
Google Map
"""
def map_hello_world(request):
    """
    Renders a page with embedded Google map. Passes variables to the associated html template via dictionary
    'context'. The URL associated with this view function is defined in urls.py.
    """

    context = {
        "google_api_key": settings.GOOGLE_API_KEY,
        "lat_coord": 29.4190,
        "lng_coord": -98.4836,
    }
    return render(request, 'map/map_index.html', context)


"""
AJAX testing.
"""
def ajax_view(request):
    return render(request, 'map/ajax_test_1.html')


def ajax_background_request_handler(request):
    """
    Handles ajax requests sent in background while user is on webpage rendered by ajax_view.
    :param request:
    :return:
    """
    if request.method == 'GET':
        data_attribute = request.GET.get('some_attribute')
        return HttpResponse(f"The number sent to the server via AJAX (GET) is: {data_attribute}")
    elif request.method == 'POST':
        data_attribute = request.POST.get('some_attribute')
        return HttpResponse(f"The number sent to the server via AJAX (POST) is: {data_attribute}")
    else:
        return HttpResponse("Error: Didn't receive data.")


# Location AJAX Testing
def location_view(request):
    return render(request, 'map/location_ajax_test.html')

def location_test_ajax_handler(request):
    """
    Handles ajax requests sent in background while user is on webpage rendered by ajax_view.
    :param request:
    :return:
    """
    if request.method == 'GET':
        user_lat = request.GET.get('user_lat')
        user_lng = request.GET.get('user_lng')
        return HttpResponse(f"The user's latitude is {user_lat}, longitude is {user_lng}")
    else:
        return HttpResponse("Error: Didn't receive data.")


"""
Socket testing.
"""
votes = {"yes": 0, "no": 0, "maybe": 0}
user_location = {"user_lat": "nothing yet", "user_lng": "nothing yet"}

# Basic socket testing
def socket_view(request):
    return render(request, 'map/sockettest.html', {"votes": votes, "user_location": user_location})


@sio.event
def submit_vote(sid, data):
    votes[data] += 1
    sio.emit("vote totals", votes)



# Socket testing with user location
def location_socket_view(request):
    return render(request, 'map/location_sockettest.html', {"user_location": user_location})


@sio.event
def broadcast_location(sid, data):
    # Update dictionary
    user_location["user_lat"] = data.get('user_lat')
    user_location["user_lng"] = data.get('user_lng')
    sio.emit("display location", user_location)

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- socket.io -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.5.1/socket.io.js" integrity="sha512-9mpsATI0KClwt+xVZfbcf2lJ8IFBAwsubJ6mI3rtULwyM3fBmQFzj0It4tGqxLOGQwGfJdk/G+fANnxfq9/cew==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- jquery, ajax -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Bootstrap5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    {% block extend_head %}
    {% endblock %}

  </head>
  <body>
    {% include 'main/navbar.html' %}
    <br>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

      <!-- Bootstrap5 JS (navbar collapse won't work without it; docs say to but before closing body tag) -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}

    <script>
        document.addEventListener('DOMContentLoaded', function() {

            document.querySelector('#red').onclick = function() {
                document.querySelector('#hello').style.color = 'red';
            };

            document.querySelector('#green').onclick = function() {
                document.querySelector('#hello').style.color = 'green';
            };

            document.querySelector('#blue').onclick = function() {
                document.querySelector('#hello').style.color = 'blue';
            };

        });

    </script>

{% endblock %}


{% block content %}
    <div class="container">
        <h1 id="hello">Javascript Demo.</h1>
        <button id="red">Red</button>
        <button id="green">Green</button>
        <button id="blue">Blue</button>
    </div>

{% endblock %}

main/templates/main/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'map:map'%}">Map</a>
        <a class="nav-link" href="{% url 'map:ajax-page' %}">AJAX Test</a>
        <a class="nav-link" href="{% url 'map:socket-page' %}">Socket Test</a>
        <a class="nav-link" href="{% url 'map:location-page' %}">Location Test</a>
        <a class="nav-link" href="{% url 'map:location-socket-page' %}">Location Socket Test</a>
      </div>
    </div>
  </div>
</nav>

map/templates/map/ajax_test_1.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}

    {% csrf_token %}
    <script type="text/javascript" charset="utf-8">

        document.addEventListener('DOMContentLoaded', () => {

            const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
            let target_element = document.querySelector('#add-html-here');

            jQuery.ajax({
                url: "{% url 'map:ajax-hidden' %}",
                headers: {'X-CSRFToken': csrftoken},
                data: {'some_attribute': 4567 },
                type: "POST",
                //dataType: 'json', // dataType specifies the type of data expected back from the server,
                dataType: 'html',  // in this example HTML data is sent back via HttpResponse in views.py
                success: callbackFunc,
            });

            function callbackFunc(data) {
                if (data) {
                    console.log("SUCCESS!");
                    // call function to do something with data
                    target_element.innerHTML = data;
                } else {
                    console.log("FAILURE!");
                }
            }
        });

    </script>

{% endblock %}


{% block content %}

    <div class="container">
        <h4>AJAX test:</h4>
        <div id="add-html-here">
            <!-- This is where we want to render new html -->
        </div>
    </div>

{% endblock %}

map/templates/map/complete_html_examplemap.html
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 8
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
    async defer></script>
  </body>
</html>

map/templates/map/location_ajax_test.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}

    <script type="text/javascript" charset="utf-8">

        document.addEventListener('DOMContentLoaded', () => {

            let iteration = 0;
            let target_element = document.querySelector('#add-html-here');

            const target = {
                latitude: 0,
                longitude: 0
            };

            const options = {
                enableHighAccuracy: true,
                //timeout: 5000,
                maximumAge: 60000,
            };

            const id = navigator.geolocation.watchPosition(posChangeCallback, error, options);

            function posChangeCallback(pos) {
                iteration += 1;
                console.log(`watchLocation success callback has been called ${iteration} times`)
                const crd = pos.coords;

                jQuery.ajax({
                    url: "{% url 'map:location-ajax' %}",
                    data: {'user_lat': crd.latitude, 'user_lng': crd.longitude },
                    type: "GET",
                    //dataType: 'json', // dataType specifies the type of data expected back from the server,
                    dataType: 'html',  // in this example HTML data is sent back via HttpResponse in views.py
                    success: ajaxCallback,
                });

            }

            function error(err) {
              console.warn('ERROR(' + err.code + '): ' + err.message);
            }

            function ajaxCallback(data) {
                target_element.innerHTML = data;
            }

        });

    </script>
{% endblock %}


{% block content %}

    <div class="container">
        <h4>Location AJAX test:</h4>
        <div id="add-html-here">
            <!-- This is where we want to render new html -->
        </div>
    </div>

{% endblock %}

map/templates/map/location_sockettest.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}

    <script type="text/javascript" charset="utf-8">
        document.addEventListener('DOMContentLoaded', () => {
            // Connect to websocket
            var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port);
            let iteration = 0;

            const options = {
                enableHighAccuracy: true,
                timeout: 5000,
                maximumAge: 60000,
            };

            function error(err) {
              console.warn('ERROR(' + err.code + '): ' + err.message);
            }

            // When connected, configure buttons
            socket.on('connect', () => {

                const id = navigator.geolocation.watchPosition(posChangeCallback, error, options);

                function posChangeCallback(pos) {
                    iteration += 1;
                    console.log(`watchLocation success callback has been called ${iteration} times`)
                    const crd = pos.coords;
                    socket.emit('broadcast_location', {'user_lat': crd.latitude, 'user_lng': crd.longitude })
                }

            });

            socket.on('display location', data => {
                document.querySelector('#user-lat').innerHTML = data.user_lat;
                document.querySelector('#user-lng').innerHTML = data.user_lng;
            });

        });

    </script>

{% endblock %}


{% block content %}
   <div class="container">
        <h5>Location Socket test:</h5>
        <div>User latitude: <span id="user-lat">{{ user_location.user_lat }}</span></div>
        <div>User longitude: <span id="user-lng">{{ user_location.user_lng }}</span></div>
    </div>

{% endblock %}

map/templates/map/map.html
{% extends "main/base.html" %}
{% load static %}

  {% block extend_head %}
    <title>Simple Map</title>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 80vh;  // do not use Google's suggested height of 100%, map won't display
      }

    </style>

    {% endblock %}

    {% block content %}

      <div class="container">
        <div id="map"></div>

        <script type="text/javascript">
            // these javascript variables must be defined here in this template
            // so the variables from the view functions can be used
            var latitude = {{lat_coord|safe}};
            var longitude = {{lng_coord|safe}};
        </script>
        <script src="{% static 'map/js/map.js' %}"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key={{ google_api_key|safe }}&callback=initMap"
        async defer></script>

      </div>


  {% endblock %}

map/templates/map/map_index.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}
    <title>Add Map</title>
      {#   I don't think the following script is needed. Map still loads.   #}
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

    <style>
      /* Always set the mapindex height explicitly to define the size of the div
       * element that contains the mapindex. */
        #map {
            height: 80vh;  /* Google's suggested height of 100% may prevent map from displaying */
        }
    </style>

    <script type="text/javascript">
        const marker_coords = {lat: {{ lat_coord }}, lng: {{ lng_coord }} }
    </script>

    <script type="module" src="{% static 'map/js/map_index.js' %}"></script>

{% endblock %}


{% block content %}
    <h3>My Google Maps Demo</h3>
    <!--The div element for the mapindex -->
    <div id="map"></div>

    <!--
     The `defer` attribute causes the callback to execute after the full HTML
     document has been parsed. For non-blocking uses, avoiding race conditions,
     and consistent behavior across browsers, consider loading using Promises
     with https://www.npmjs.com/package/@googlemaps/js-api-loader.

     DO NOT use the `async` attribute that is shown in some example html in Google's tutorials, the map may not
     load.
    -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key={{ google_api_key|safe }}&callback=initMap&v=weekly" defer>
    </script>

{% endblock %}

map/templates/map/sockettest.html
{% extends "main/base.html" %}
{% load static %}

{% block extend_head %}

    <script type="text/javascript" charset="utf-8">
        document.addEventListener('DOMContentLoaded', () => {
            // Connect to websocket
            var socket = io.connect(location.protocol + '//' + document.domain + ':' + location.port);

            // When connected, configure buttons
            socket.on('connect', () => {
                // Each button should emit a "submit vote" event
                document.querySelectorAll('button').forEach(button => {
                    button.onclick = () => {
                        const selection = button.dataset.vote;
                        socket.emit('submit_vote', selection); // submit_vote is the server-side socket event handler
                        // function defined in map/views.py
                    };
                });
            });

            socket.on('vote totals', data => {
                document.querySelector('#yes').innerHTML = data.yes;
                document.querySelector('#no').innerHTML = data.no;
                document.querySelector('#maybe').innerHTML = data.maybe;
            });

            socket.on('display location', data => {
                document.querySelector('#user-lat').innerHTML = data.user_lat;
                document.querySelector('#user-lng').innerHTML = data.user_lng;
            });

        });

    </script>

{% endblock %}


{% block content %}
    <div class="container">
        <h6>
            Open current URL in another window (even in a different browser) and you will see that the votes are
            immediately broadcast to every window.
        </h6>
        <div>Yes Votes: <span id="yes">{{ votes.yes }}</span></div>
        <div>No Votes: <span id="no">{{ votes.no }}</span></div>
        <div>Maybe Votes: <span id="maybe">{{ votes.maybe }}</span></div>
        <br>
        <button data-vote="yes">Yes</button>
        <button data-vote="no">No</button>
        <button data-vote="maybe">Maybe</button>

    </div>
    <br><br>
   <div class="container">
        <h5>Location Socket test:</h5>
        <div>User latitude: <span id="user-lat">{{ user_location.user_lat }}</span></div>
        <div>User longitude: <span id="user-lng">{{ user_location.user_lng }}</span></div>
    </div>

{% endblock %}